[alias]
a = "add"
au = "audit"
b = "build"
br = "build --release"
brr = "build --release"
c = "check"
d = "doc"
dd = "watch -x doc"
f = "fmt"
i = "install"
lock = "generate-lockfile"
m = "msrv"
n = "new"
o = "outdated -Rv"
pp = "clippy"
r = "run"
rr = "run --release"
se = "search"
t = "nextest run"
trp = "tarpaulin -o Xml -v"
upd = "update"
updr = "update --dry-run"
upg = "upgrade"
w = "watch"

# [build]
# target-dir = "projects/.cargo/target"
# rustflags = ["-Z", "threads=8"]

[net]
git-fetch-with-cli = true

# [unstable]
# gc = true
