[tools]
"cargo:atuin" = "latest"
"cargo:bat" = "latest"
"cargo:bottom" = "latest"
"cargo:cargo-generate" = "latest"
"cargo:cargo-get" = "latest"
"cargo:cargo-make" = "latest"
"cargo:cargo-outdated" =  { version = "latest", locked = false }
"cargo:cargo-rdme" = "latest"
"cargo:cargo-semver-checks" = "latest"
"cargo:cargo-udeps" = "latest"
"cargo:cargo-update" = "latest"
"cargo:cargo-workspaces" = "latest"
"cargo:eza" = "latest"
"cargo:fd-find" = "latest"
"cargo:fnm" = "latest"
"cargo:fsays" = "latest"
"cargo:git-delta" = "latest"
"cargo:intelli-shell" = "latest"
"cargo:just" = "latest"
"cargo:kanidm_tools" = "latest"
"cargo:mdbook" = "latest"
"cargo:mdsf" = "latest"
"cargo:nu" = "latest"
"cargo:ouch" = "latest"
"cargo:presenterm" = "latest"
"cargo:ripgrep" = "latest"
"cargo:rustic-rs" = "latest"
"cargo:sd" = "latest"
"cargo:shellharden" = "latest"
"cargo:sqlx-cli" = "latest"
"cargo:starship" = "latest"
"cargo:stylua" = "latest"
"cargo:tealdeer" = "latest"
"cargo:tree-sitter-cli" = "latest"
"cargo:typos-cli" = "latest"
"cargo:typst-cli" = "latest"
"cargo:typst-lsp" = "latest"
"cargo:typstyle" = "latest"
"cargo:yazi-cli" = "latest"
"cargo:yazi-fm" = "latest"
"cargo:zellij" = "latest"
"cargo:zoxide" = "latest"
"go:github.com/abenz1267/gomvp" = "latest"
"go:github.com/abice/go-enum" = "latest"
"go:github.com/charmbracelet/glow" = "latest"
"go:github.com/cloudflare/cloudflare-go/cmd/flarectl" = "latest"
"go:github.com/cweill/gotests/gotests" = "latest"
"go:github.com/dancnb/sonicradio" = "latest"
"go:github.com/davidrjenni/reftools/cmd/fillstruct" = "latest"
"go:github.com/davidrjenni/reftools/cmd/fillswitch" = "latest"
"go:github.com/davidrjenni/reftools/cmd/fixplurals" = "latest"
"go:github.com/fatih/gomodifytags" = "latest"
"go:github.com/golangci/golangci-lint/cmd/golangci-lint" = "latest"
"go:github.com/google/yamlfmt/cmd/yamlfmt" = "latest"
"go:github.com/jesseduffield/lazydocker" = "latest"
"go:github.com/jesseduffield/lazygit" = "latest"
"go:github.com/josharian/impl" = "latest"
"go:github.com/joshmedeski/sesh" = "latest"
"go:github.com/koron/iferr" = "latest"
"go:github.com/kubernetes/kompose" = "latest"
"go:github.com/kyoh86/richgo" = "latest"
"go:github.com/mikefarah/yq/v4" = "latest"
"go:github.com/nats-io/natscli/nats" = "latest"
"go:github.com/onsi/ginkgo/v2/ginkgo" = "latest"
"go:github.com/segmentio/golines" = "latest"
"go:github.com/tmc/json-to-struct" = "latest"
"go:go.uber.org/mock/mockgen" = "latest"
"go:golang.org/x/tools/cmd/callgraph" = "latest"
"go:golang.org/x/tools/cmd/deadcode" = "latest"
"go:golang.org/x/tools/cmd/digraph" = "latest"
"go:golang.org/x/tools/cmd/fiximports" = "latest"
"go:golang.org/x/tools/cmd/goimports" = "latest"
"go:golang.org/x/tools/cmd/gorename" = "latest"
"go:golang.org/x/tools/cmd/stringer" = "latest"
"go:golang.org/x/tools/cmd/toolstash" = "latest"
"go:golang.org/x/vuln/cmd/govulncheck" = "latest"
"go:gotest.tools/gotestsum" = "latest"
"go:mvdan.cc/gofumpt" = "latest"
"go:mvdan.cc/sh/v3/cmd/shfmt" = "latest"
"pipx:anthropic-cli" = "latest"
"pipx:black" = "latest"
"pipx:codespell" = "latest"
"pipx:cqlsh" = "latest"
"pipx:isort" = "latest"
"pipx:jrnl" = "latest"
"pipx:mdformat" = "latest"
"pipx:mutagen" = "latest"
"pipx:openai" = "latest"
"pipx:podman-compose" = "latest"
"pipx:pre-commit" = "latest"
"pipx:ruff" = "latest"
"pipx:shandy-sqlfmt" = "latest"
"pipx:thefuck" = { version = "latest", uvx_args = "-p 3.11" }
"pipx:yamlfix" = "latest"
bun = "latest"
cargo-binstall = "latest"
choose = "latest"
go = "latest"
kustomize = "latest"
opentofu = "latest"
uv = "latest"

[settings]
activate_aggressive = true
npm = { bun = true }
pipx = { uvx = true }
python = { uv_venv_auto = true }
status = { show_env = true, show_tools = false }
experimental = true

