[tools]
"cargo:atuin" = "latest"
"cargo:bat" = "latest"
"cargo:bottom" = "latest"
"cargo:cargo-generate" = "latest"
"cargo:cargo-get" = "latest"
"cargo:cargo-make" = "latest"
"cargo:cargo-outdated" =  { version = "latest", locked = false }
"cargo:cargo-rdme" = "latest"
"cargo:cargo-semver-checks" = "latest"
"cargo:cargo-udeps" = "latest"
"cargo:cargo-update" = "latest"
"cargo:cargo-workspaces" = "latest"
"cargo:eza" = "latest"
"cargo:fd-find" = "latest"
"cargo:fnm" = "latest"
"cargo:fsays" = "latest"
"cargo:git-delta" = "latest"
"cargo:intelli-shell" = "latest"
"cargo:just" = "latest"
"cargo:kanidm_tools" = "latest"
"cargo:mdbook" = "latest"
"cargo:mdsf" = "latest"
"cargo:nu" = "latest"
"cargo:ouch" = "latest"
"cargo:presenterm" = "latest"
"cargo:ripgrep" = "latest"
"cargo:rustic-rs" = "latest"
"cargo:sd" = "latest"
"cargo:shellharden" = "latest"
"cargo:sqlx-cli" = "latest"
"cargo:starship" = "latest"
"cargo:stylua" = "latest"
"cargo:tealdeer" = "latest"
"cargo:tree-sitter-cli" = "latest"
"cargo:typos-cli" = "latest"
"cargo:typst-cli" = "latest"
"cargo:typst-lsp" = "latest"
"cargo:typstyle" = "latest"
"cargo:yazi-cli" = "latest"
"cargo:yazi-fm" = "latest"
"cargo:zellij" = "latest"
"cargo:zoxide" = "latest"
"pipx:anthropic-cli" = "latest"
"pipx:black" = "latest"
"pipx:codespell" = "latest"
"pipx:cqlsh" = "latest"
"pipx:isort" = "latest"
"pipx:jrnl" = "latest"
"pipx:mdformat" = "latest"
"pipx:mutagen" = "latest"
"pipx:openai" = "latest"
"pipx:podman-compose" = "latest"
"pipx:pre-commit" = "latest"
"pipx:ruff" = "latest"
"pipx:shandy-sqlfmt" = "latest"
"pipx:thefuck" = { version = "latest", uvx_args = "-p 3.11" }
"pipx:yamlfix" = "latest"
bun = "latest"
cargo-binstall = "latest"
choose = "latest"
go = "latest"
kustomize = "latest"
opentofu = "latest"
uv = "latest"

[settings]
activate_aggressive = true
npm = { bun = true }
pipx = { uvx = true }
python = { uv_venv_auto = true }
status = { show_env = true, show_tools = false }
experimental = true

