[settings]
activate_aggressive = true
npm = { bun = true }
pipx = { uvx = true }
python = { uv_venv_auto = true }
status = { show_env = true, show_tools = false }
experimental = true

[tools]
"pipx:anthropic-cli" = "latest"
"pipx:black" = "latest"
"pipx:codespell" = "latest"
"pipx:cqlsh" = "latest"
"pipx:isort" = "latest"
"pipx:jrnl" = "latest"
"pipx:mdformat" = "latest"
"pipx:mutagen" = "latest"
"pipx:openai" = "latest"
"pipx:podman-compose" = "latest"
"pipx:pre-commit" = "latest"
"pipx:ruff" = "latest"
"pipx:shandy-sqlfmt" = "latest"
"pipx:thefuck" = { version = "latest", uvx_args = "-p 3.11" }
"pipx:yamlfix" = "latest"
"pipx:sqlfluff" = "latest"
"pipx:httpie" = "latest"
bun = "latest"
choose = "latest"
kustomize = "latest"
opentofu = "latest"
uv = "latest"
